// Static champion list — updated from Data Dragon periodically.
// Used as fallback when network is unavailable (corporate proxy, etc.)
// Images are loaded separately from ddragon.leagueoflegends.com CDN.

export type ChampionStatic = { id: string; name: string; cls: string }

export const CHAMPIONS_STATIC: ChampionStatic[] = [
  { id: 'Aatrox',       name: 'Aatrox',         cls: 'fighter'   },
  { id: 'Ahri',         name: 'Ahri',            cls: 'mage'      },
  { id: 'Akali',        name: 'Akali',           cls: 'assassin'  },
  { id: 'Akshan',       name: 'Akshan',          cls: 'marksman'  },
  { id: 'Alistar',      name: 'Alistar',         cls: 'tank'      },
  { id: 'Ambessa',      name: 'Ambessa',         cls: 'fighter'   },
  { id: 'Amumu',        name: 'Amumu',           cls: 'tank'      },
  { id: 'Anivia',       name: 'Anivia',          cls: 'mage'      },
  { id: 'Annie',        name: 'Annie',           cls: 'mage'      },
  { id: 'Aphelios',     name: 'Aphelios',        cls: 'marksman'  },
  { id: 'Ashe',         name: 'Ashe',            cls: 'marksman'  },
  { id: 'AurelionSol',  name: 'Aurelion Sol',    cls: 'mage'      },
  { id: 'Aurora',       name: 'Aurora',          cls: 'mage'      },
  { id: 'Azir',         name: 'Azir',            cls: 'mage'      },
  { id: 'Bard',         name: 'Bard',            cls: 'support'   },
  { id: 'BelVeth',      name: "Bel'Veth",        cls: 'fighter'   },
  { id: 'Blitzcrank',   name: 'Blitzcrank',      cls: 'tank'      },
  { id: 'Brand',        name: 'Brand',           cls: 'mage'      },
  { id: 'Braum',        name: 'Braum',           cls: 'support'   },
  { id: 'Briar',        name: 'Briar',           cls: 'assassin'  },
  { id: 'Caitlyn',      name: 'Caitlyn',         cls: 'marksman'  },
  { id: 'Camille',      name: 'Camille',         cls: 'fighter'   },
  { id: 'Cassiopeia',   name: 'Cassiopeia',      cls: 'mage'      },
  { id: 'ChoGath',      name: "Cho'Gath",        cls: 'tank'      },
  { id: 'Corki',        name: 'Corki',           cls: 'marksman'  },
  { id: 'Darius',       name: 'Darius',          cls: 'fighter'   },
  { id: 'Diana',        name: 'Diana',           cls: 'assassin'  },
  { id: 'DrMundo',      name: 'Dr. Mundo',       cls: 'tank'      },
  { id: 'Draven',       name: 'Draven',          cls: 'marksman'  },
  { id: 'Ekko',         name: 'Ekko',            cls: 'assassin'  },
  { id: 'Elise',        name: 'Elise',           cls: 'mage'      },
  { id: 'Evelynn',      name: 'Evelynn',         cls: 'assassin'  },
  { id: 'Ezreal',       name: 'Ezreal',          cls: 'marksman'  },
  { id: 'Fiddlesticks', name: 'Fiddlesticks',    cls: 'mage'      },
  { id: 'Fiora',        name: 'Fiora',           cls: 'fighter'   },
  { id: 'Fizz',         name: 'Fizz',            cls: 'assassin'  },
  { id: 'Galio',        name: 'Galio',           cls: 'tank'      },
  { id: 'Gangplank',    name: 'Gangplank',       cls: 'fighter'   },
  { id: 'Garen',        name: 'Garen',           cls: 'tank'      },
  { id: 'Gnar',         name: 'Gnar',            cls: 'fighter'   },
  { id: 'Gragas',       name: 'Gragas',          cls: 'fighter'   },
  { id: 'Graves',       name: 'Graves',          cls: 'marksman'  },
  { id: 'Gwen',         name: 'Gwen',            cls: 'fighter'   },
  { id: 'Hecarim',      name: 'Hecarim',         cls: 'fighter'   },
  { id: 'Heimerdinger', name: 'Heimerdinger',    cls: 'mage'      },
  { id: 'Hwei',         name: 'Hwei',            cls: 'mage'      },
  { id: 'Illaoi',       name: 'Illaoi',          cls: 'fighter'   },
  { id: 'Irelia',       name: 'Irelia',          cls: 'fighter'   },
  { id: 'Ivern',        name: 'Ivern',           cls: 'support'   },
  { id: 'Janna',        name: 'Janna',           cls: 'support'   },
  { id: 'JarvanIV',     name: 'Jarvan IV',       cls: 'tank'      },
  { id: 'Jax',          name: 'Jax',             cls: 'fighter'   },
  { id: 'Jayce',        name: 'Jayce',           cls: 'fighter'   },
  { id: 'Jhin',         name: 'Jhin',            cls: 'marksman'  },
  { id: 'Jinx',         name: 'Jinx',            cls: 'marksman'  },
  { id: 'KSante',       name: "K'Sante",         cls: 'tank'      },
  { id: 'KaiSa',        name: "Kai'Sa",          cls: 'marksman'  },
  { id: 'Kalista',      name: 'Kalista',         cls: 'marksman'  },
  { id: 'Karma',        name: 'Karma',           cls: 'support'   },
  { id: 'Karthus',      name: 'Karthus',         cls: 'mage'      },
  { id: 'Kassadin',     name: 'Kassadin',        cls: 'assassin'  },
  { id: 'Katarina',     name: 'Katarina',        cls: 'assassin'  },
  { id: 'Kayle',        name: 'Kayle',           cls: 'fighter'   },
  { id: 'Kayn',         name: 'Kayn',            cls: 'assassin'  },
  { id: 'Kennen',       name: 'Kennen',          cls: 'mage'      },
  { id: 'KhaZix',       name: "Kha'Zix",         cls: 'assassin'  },
  { id: 'Kindred',      name: 'Kindred',         cls: 'marksman'  },
  { id: 'Kled',         name: 'Kled',            cls: 'fighter'   },
  { id: 'KogMaw',       name: "Kog'Maw",         cls: 'marksman'  },
  { id: 'Leblanc',      name: 'LeBlanc',         cls: 'assassin'  },
  { id: 'LeeSin',       name: 'Lee Sin',         cls: 'fighter'   },
  { id: 'Leona',        name: 'Leona',           cls: 'tank'      },
  { id: 'Lillia',       name: 'Lillia',          cls: 'mage'      },
  { id: 'Lissandra',    name: 'Lissandra',       cls: 'mage'      },
  { id: 'Lucian',       name: 'Lucian',          cls: 'marksman'  },
  { id: 'Lulu',         name: 'Lulu',            cls: 'support'   },
  { id: 'Lux',          name: 'Lux',             cls: 'mage'      },
  { id: 'Malphite',     name: 'Malphite',        cls: 'tank'      },
  { id: 'Malzahar',     name: 'Malzahar',        cls: 'mage'      },
  { id: 'Maokai',       name: 'Maokai',          cls: 'tank'      },
  { id: 'MasterYi',     name: 'Master Yi',       cls: 'assassin'  },
  { id: 'Mel',          name: 'Mel',             cls: 'mage'      },
  { id: 'Milio',        name: 'Milio',           cls: 'support'   },
  { id: 'MissFortune',  name: 'Miss Fortune',    cls: 'marksman'  },
  { id: 'Mordekaiser',  name: 'Mordekaiser',     cls: 'fighter'   },
  { id: 'Morgana',      name: 'Morgana',         cls: 'support'   },
  { id: 'Naafiri',      name: 'Naafiri',         cls: 'assassin'  },
  { id: 'Nami',         name: 'Nami',            cls: 'support'   },
  { id: 'Nasus',        name: 'Nasus',           cls: 'fighter'   },
  { id: 'Nautilus',     name: 'Nautilus',        cls: 'tank'      },
  { id: 'Neeko',        name: 'Neeko',           cls: 'mage'      },
  { id: 'Nidalee',      name: 'Nidalee',         cls: 'assassin'  },
  { id: 'Nilah',        name: 'Nilah',           cls: 'fighter'   },
  { id: 'Nocturne',     name: 'Nocturne',        cls: 'assassin'  },
  { id: 'Nunu',         name: 'Nunu',            cls: 'tank'      },
  { id: 'Olaf',         name: 'Olaf',            cls: 'fighter'   },
  { id: 'Orianna',      name: 'Orianna',         cls: 'mage'      },
  { id: 'Ornn',         name: 'Ornn',            cls: 'tank'      },
  { id: 'Pantheon',     name: 'Pantheon',        cls: 'fighter'   },
  { id: 'Poppy',        name: 'Poppy',           cls: 'tank'      },
  { id: 'Pyke',         name: 'Pyke',            cls: 'assassin'  },
  { id: 'Qiyana',       name: 'Qiyana',          cls: 'assassin'  },
  { id: 'Quinn',        name: 'Quinn',           cls: 'marksman'  },
  { id: 'Rakan',        name: 'Rakan',           cls: 'support'   },
  { id: 'Rammus',       name: 'Rammus',          cls: 'tank'      },
  { id: 'RekSai',       name: "Rek'Sai",         cls: 'fighter'   },
  { id: 'Rell',         name: 'Rell',            cls: 'tank'      },
  { id: 'Renata',       name: 'Renata Glasc',    cls: 'support'   },
  { id: 'Renekton',     name: 'Renekton',        cls: 'fighter'   },
  { id: 'Rengar',       name: 'Rengar',          cls: 'assassin'  },
  { id: 'Riven',        name: 'Riven',           cls: 'fighter'   },
  { id: 'Rumble',       name: 'Rumble',          cls: 'mage'      },
  { id: 'Ryze',         name: 'Ryze',            cls: 'mage'      },
  { id: 'Samira',       name: 'Samira',          cls: 'marksman'  },
  { id: 'Sejuani',      name: 'Sejuani',         cls: 'tank'      },
  { id: 'Senna',        name: 'Senna',           cls: 'support'   },
  { id: 'Seraphine',    name: 'Seraphine',       cls: 'support'   },
  { id: 'Sett',         name: 'Sett',            cls: 'fighter'   },
  { id: 'Shaco',        name: 'Shaco',           cls: 'assassin'  },
  { id: 'Shen',         name: 'Shen',            cls: 'tank'      },
  { id: 'Shyvana',      name: 'Shyvana',         cls: 'fighter'   },
  { id: 'Singed',       name: 'Singed',          cls: 'tank'      },
  { id: 'Sion',         name: 'Sion',            cls: 'tank'      },
  { id: 'Sivir',        name: 'Sivir',           cls: 'marksman'  },
  { id: 'Skarner',      name: 'Skarner',         cls: 'tank'      },
  { id: 'Smolder',      name: 'Smolder',         cls: 'marksman'  },
  { id: 'Sona',         name: 'Sona',            cls: 'support'   },
  { id: 'Soraka',       name: 'Soraka',          cls: 'support'   },
  { id: 'Swain',        name: 'Swain',           cls: 'mage'      },
  { id: 'Sylas',        name: 'Sylas',           cls: 'mage'      },
  { id: 'Syndra',       name: 'Syndra',          cls: 'mage'      },
  { id: 'TahmKench',    name: 'Tahm Kench',      cls: 'tank'      },
  { id: 'Taliyah',      name: 'Taliyah',         cls: 'mage'      },
  { id: 'Talon',        name: 'Talon',           cls: 'assassin'  },
  { id: 'Taric',        name: 'Taric',           cls: 'support'   },
  { id: 'Teemo',        name: 'Teemo',           cls: 'marksman'  },
  { id: 'Thresh',       name: 'Thresh',          cls: 'support'   },
  { id: 'Tristana',     name: 'Tristana',        cls: 'marksman'  },
  { id: 'Trundle',      name: 'Trundle',         cls: 'fighter'   },
  { id: 'Tryndamere',   name: 'Tryndamere',      cls: 'fighter'   },
  { id: 'TwistedFate',  name: 'Twisted Fate',    cls: 'mage'      },
  { id: 'Twitch',       name: 'Twitch',          cls: 'marksman'  },
  { id: 'Udyr',         name: 'Udyr',            cls: 'fighter'   },
  { id: 'Urgot',        name: 'Urgot',           cls: 'fighter'   },
  { id: 'Varus',        name: 'Varus',           cls: 'marksman'  },
  { id: 'Vayne',        name: 'Vayne',           cls: 'marksman'  },
  { id: 'Veigar',       name: 'Veigar',          cls: 'mage'      },
  { id: 'VelKoz',       name: "Vel'Koz",         cls: 'mage'      },
  { id: 'Vex',          name: 'Vex',             cls: 'mage'      },
  { id: 'Vi',           name: 'Vi',              cls: 'fighter'   },
  { id: 'Viego',        name: 'Viego',           cls: 'assassin'  },
  { id: 'Viktor',       name: 'Viktor',          cls: 'mage'      },
  { id: 'Vladimir',     name: 'Vladimir',        cls: 'mage'      },
  { id: 'Volibear',     name: 'Volibear',        cls: 'fighter'   },
  { id: 'Warwick',      name: 'Warwick',         cls: 'fighter'   },
  { id: 'Wukong',       name: 'Wukong',          cls: 'fighter'   },
  { id: 'Xayah',        name: 'Xayah',           cls: 'marksman'  },
  { id: 'Xerath',       name: 'Xerath',          cls: 'mage'      },
  { id: 'XinZhao',      name: 'Xin Zhao',        cls: 'fighter'   },
  { id: 'Yasuo',        name: 'Yasuo',           cls: 'fighter'   },
  { id: 'Yone',         name: 'Yone',            cls: 'fighter'   },
  { id: 'Yorick',       name: 'Yorick',          cls: 'fighter'   },
  { id: 'Yuumi',        name: 'Yuumi',           cls: 'support'   },
  { id: 'Zac',          name: 'Zac',             cls: 'tank'      },
  { id: 'Zed',          name: 'Zed',             cls: 'assassin'  },
  { id: 'Zeri',         name: 'Zeri',            cls: 'marksman'  },
  { id: 'Ziggs',        name: 'Ziggs',           cls: 'mage'      },
  { id: 'Zilean',       name: 'Zilean',          cls: 'support'   },
  { id: 'Zoe',          name: 'Zoe',             cls: 'mage'      },
  { id: 'Zyra',         name: 'Zyra',            cls: 'mage'      },
]
