// Champion class lookup — port de tokens.jsx v13 (CHAMPS + CLASS_COLORS)
// Tag = 2 lettres pour ChampionTile, cls = classe pour couleur de fond

export const CLASS_COLORS: Record<string, string> = {
  assassin: '#ff5577',
  fighter:  '#ff8a3d',
  mage:     '#7c5cff',
  marksman: '#ffd166',
  support:  '#3ddc97',
  tank:     '#5fa8ff',
}

type ChampData = { name: string; cls: keyof typeof CLASS_COLORS; tag: string }

// Clés en minuscules — match champPool keys (Aatrox → aatrox)
const CHAMPS_RAW: Record<string, ChampData> = {
  // ── Top
  aatrox:       { name: 'Aatrox',       cls: 'fighter',  tag: 'AA' },
  camille:      { name: 'Camille',      cls: 'fighter',  tag: 'CM' },
  chogath:      { name: "Cho'Gath",     cls: 'tank',     tag: 'CG' },
  darius:       { name: 'Darius',       cls: 'fighter',  tag: 'DA' },
  fiora:        { name: 'Fiora',        cls: 'fighter',  tag: 'FI' },
  gangplank:    { name: 'Gangplank',    cls: 'fighter',  tag: 'GP' },
  garen:        { name: 'Garen',        cls: 'tank',     tag: 'GR' },
  gnar:         { name: 'Gnar',         cls: 'fighter',  tag: 'GN' },
  gragas:       { name: 'Gragas',       cls: 'fighter',  tag: 'GG' },
  illaoi:       { name: 'Illaoi',       cls: 'fighter',  tag: 'IL' },
  irelia:       { name: 'Irelia',       cls: 'fighter',  tag: 'IR' },
  jax:          { name: 'Jax',          cls: 'fighter',  tag: 'JA' },
  jayce:        { name: 'Jayce',        cls: 'fighter',  tag: 'JY' },
  kennen:       { name: 'Kennen',       cls: 'mage',     tag: 'KN' },
  kled:         { name: 'Kled',         cls: 'fighter',  tag: 'KL' },
  malphite:     { name: 'Malphite',     cls: 'tank',     tag: 'ML' },
  maokai:       { name: 'Maokai',       cls: 'tank',     tag: 'MK' },
  mordekaiser:  { name: 'Mordekaiser',  cls: 'fighter',  tag: 'MO' },
  nasus:        { name: 'Nasus',        cls: 'fighter',  tag: 'NS' },
  nautilus:     { name: 'Nautilus',     cls: 'tank',     tag: 'NT' },
  olaf:         { name: 'Olaf',         cls: 'fighter',  tag: 'OL' },
  ornn:         { name: 'Ornn',         cls: 'tank',     tag: 'OR' },
  pantheon:     { name: 'Pantheon',     cls: 'fighter',  tag: 'PT' },
  quinn:        { name: 'Quinn',        cls: 'marksman', tag: 'QN' },
  renekton:     { name: 'Renekton',     cls: 'fighter',  tag: 'RK' },
  riven:        { name: 'Riven',        cls: 'fighter',  tag: 'RV' },
  rumble:       { name: 'Rumble',       cls: 'fighter',  tag: 'RB' },
  sett:         { name: 'Sett',         cls: 'fighter',  tag: 'ST' },
  singed:       { name: 'Singed',       cls: 'tank',     tag: 'SG' },
  sion:         { name: 'Sion',         cls: 'tank',     tag: 'SI' },
  swain:        { name: 'Swain',        cls: 'mage',     tag: 'SW' },
  teemo:        { name: 'Teemo',        cls: 'marksman', tag: 'TE' },
  tryndamere:   { name: 'Tryndamere',   cls: 'fighter',  tag: 'TY' },
  urgot:        { name: 'Urgot',        cls: 'fighter',  tag: 'UG' },
  vayne:        { name: 'Vayne',        cls: 'marksman', tag: 'VY' },
  volibear:     { name: 'Volibear',     cls: 'fighter',  tag: 'VB' },
  warwick:      { name: 'Warwick',      cls: 'fighter',  tag: 'WW' },
  wukong:       { name: 'Wukong',       cls: 'fighter',  tag: 'WK' },
  // ── Jungle
  amumu:        { name: 'Amumu',        cls: 'tank',     tag: 'AM' },
  belveth:      { name: "Bel'Veth",     cls: 'fighter',  tag: 'BV' },
  briar:        { name: 'Briar',        cls: 'assassin', tag: 'BR' },
  diana:        { name: 'Diana',        cls: 'assassin', tag: 'DI' },
  ekko:         { name: 'Ekko',         cls: 'assassin', tag: 'EK' },
  elise:        { name: 'Elise',        cls: 'mage',     tag: 'EL' },
  evelynn:      { name: 'Evelynn',      cls: 'assassin', tag: 'EV' },
  fiddlesticks: { name: 'Fiddlesticks', cls: 'mage',     tag: 'FS' },
  graves:       { name: 'Graves',       cls: 'marksman', tag: 'GV' },
  hecarim:      { name: 'Hecarim',      cls: 'fighter',  tag: 'HC' },
  jarvaniv:     { name: 'Jarvan IV',    cls: 'tank',     tag: 'JV' },
  jarvan4:      { name: 'Jarvan IV',    cls: 'tank',     tag: 'JV' },
  kayn:         { name: 'Kayn',         cls: 'assassin', tag: 'KY' },
  khaZix:       { name: "Kha'Zix",      cls: 'assassin', tag: 'KZ' },
  khazix:       { name: "Kha'Zix",      cls: 'assassin', tag: 'KZ' },
  kindred:      { name: 'Kindred',      cls: 'marksman', tag: 'KD' },
  leesin:       { name: 'Lee Sin',      cls: 'fighter',  tag: 'LS' },
  lillia:       { name: 'Lillia',       cls: 'mage',     tag: 'LL' },
  masteryi:     { name: 'Master Yi',    cls: 'assassin', tag: 'MY' },
  nidalee:      { name: 'Nidalee',      cls: 'assassin', tag: 'ND' },
  nocturne:     { name: 'Nocturne',     cls: 'assassin', tag: 'NC' },
  nunu:         { name: 'Nunu',         cls: 'tank',     tag: 'NU' },
  olaf2:        { name: 'Olaf',         cls: 'fighter',  tag: 'OL' },
  pathkeepon:   { name: 'Pantheon',     cls: 'fighter',  tag: 'PT' },
  rammus:       { name: 'Rammus',       cls: 'tank',     tag: 'RM' },
  reksai:       { name: "Rek'Sai",      cls: 'fighter',  tag: 'RS' },
  rengar:       { name: 'Rengar',       cls: 'assassin', tag: 'RG' },
  sejuani:      { name: 'Sejuani',      cls: 'tank',     tag: 'SJ' },
  shaco:        { name: 'Shaco',        cls: 'assassin', tag: 'SH' },
  shyvana:      { name: 'Shyvana',      cls: 'fighter',  tag: 'SV' },
  skarner:      { name: 'Skarner',      cls: 'fighter',  tag: 'SK' },
  taliyah:      { name: 'Taliyah',      cls: 'mage',     tag: 'TL' },
  trundle:      { name: 'Trundle',      cls: 'fighter',  tag: 'TR' },
  udyr:         { name: 'Udyr',         cls: 'fighter',  tag: 'UD' },
  viego:        { name: 'Viego',        cls: 'assassin', tag: 'VG' },
  vi:           { name: 'Vi',           cls: 'fighter',  tag: 'VI' },
  volibear2:    { name: 'Volibear',     cls: 'fighter',  tag: 'VB' },
  xinzhao:      { name: 'Xin Zhao',     cls: 'fighter',  tag: 'XZ' },
  zac:          { name: 'Zac',          cls: 'tank',     tag: 'ZC' },
  // ── Mid
  ahri:         { name: 'Ahri',         cls: 'mage',     tag: 'AH' },
  akali:        { name: 'Akali',        cls: 'assassin', tag: 'AK' },
  akshan:       { name: 'Akshan',       cls: 'marksman', tag: 'AS' },
  anivia:       { name: 'Anivia',       cls: 'mage',     tag: 'AN' },
  annie:        { name: 'Annie',        cls: 'mage',     tag: 'AI' },
  aurelionSol:  { name: 'Aurelion Sol', cls: 'mage',     tag: 'AU' },
  aurelionsol:  { name: 'Aurelion Sol', cls: 'mage',     tag: 'AU' },
  azir:         { name: 'Azir',         cls: 'mage',     tag: 'AZ' },
  cassiopeia:   { name: 'Cassiopeia',   cls: 'mage',     tag: 'CS' },
  corki:        { name: 'Corki',        cls: 'marksman', tag: 'CO' },
  fizz:         { name: 'Fizz',         cls: 'assassin', tag: 'FZ' },
  galio:        { name: 'Galio',        cls: 'tank',     tag: 'GL' },
  katarina:     { name: 'Katarina',     cls: 'assassin', tag: 'KT' },
  leblanc:      { name: 'LeBlanc',      cls: 'assassin', tag: 'LB' },
  lissandra:    { name: 'Lissandra',    cls: 'mage',     tag: 'LI' },
  lux:          { name: 'Lux',          cls: 'mage',     tag: 'LX' },
  malzahar:     { name: 'Malzahar',     cls: 'mage',     tag: 'MZ' },
  naafiri:      { name: 'Naafiri',      cls: 'assassin', tag: 'NF' },
  orianna:      { name: 'Orianna',      cls: 'mage',     tag: 'OA' },
  ryze:         { name: 'Ryze',         cls: 'mage',     tag: 'RZ' },
  sylas:        { name: 'Sylas',        cls: 'mage',     tag: 'SL' },
  syndra:       { name: 'Syndra',       cls: 'mage',     tag: 'SY' },
  talon:        { name: 'Talon',        cls: 'assassin', tag: 'TA' },
  twistedfate:  { name: 'Twisted Fate', cls: 'mage',     tag: 'TF' },
  veigar:       { name: 'Veigar',       cls: 'mage',     tag: 'VE' },
  vex:          { name: 'Vex',          cls: 'mage',     tag: 'VX' },
  viktor:       { name: 'Viktor',       cls: 'mage',     tag: 'VK' },
  vladmir:      { name: 'Vladimir',     cls: 'mage',     tag: 'VL' },
  vladimir:     { name: 'Vladimir',     cls: 'mage',     tag: 'VL' },
  xerath:       { name: 'Xerath',       cls: 'mage',     tag: 'XR' },
  yasuo:        { name: 'Yasuo',        cls: 'fighter',  tag: 'YA' },
  yone:         { name: 'Yone',         cls: 'fighter',  tag: 'YO' },
  zed:          { name: 'Zed',          cls: 'assassin', tag: 'ZD' },
  zoe:          { name: 'Zoe',          cls: 'mage',     tag: 'ZO' },
  // ── ADC
  aphelios:     { name: 'Aphelios',     cls: 'marksman', tag: 'AP' },
  ashe:         { name: 'Ashe',         cls: 'marksman', tag: 'AS' },
  caitlyn:      { name: 'Caitlyn',      cls: 'marksman', tag: 'CT' },
  calebsi:      { name: 'Calebsi',      cls: 'marksman', tag: 'CB' },
  draven:       { name: 'Draven',       cls: 'marksman', tag: 'DV' },
  ezreal:       { name: 'Ezreal',       cls: 'marksman', tag: 'EZ' },
  jhin:         { name: 'Jhin',         cls: 'marksman', tag: 'JH' },
  jinx:         { name: 'Jinx',         cls: 'marksman', tag: 'JX' },
  kaisa:        { name: "Kai'Sa",       cls: 'marksman', tag: 'KS' },
  kalista:      { name: 'Kalista',      cls: 'marksman', tag: 'KA' },
  kogmaw:       { name: "Kog'Maw",      cls: 'marksman', tag: 'KM' },
  lucian:       { name: 'Lucian',       cls: 'marksman', tag: 'LC' },
  missfortune:  { name: 'Miss Fortune', cls: 'marksman', tag: 'MF' },
  nilah:        { name: 'Nilah',        cls: 'fighter',  tag: 'NL' },
  samira:       { name: 'Samira',       cls: 'marksman', tag: 'SM' },
  sivir:        { name: 'Sivir',        cls: 'marksman', tag: 'SV' },
  tristana:     { name: 'Tristana',     cls: 'marksman', tag: 'TS' },
  twitch:       { name: 'Twitch',       cls: 'assassin', tag: 'TW' },
  urgot2:       { name: 'Urgot',        cls: 'fighter',  tag: 'UG' },
  varus:        { name: 'Varus',        cls: 'marksman', tag: 'VR' },
  vayne2:       { name: 'Vayne',        cls: 'marksman', tag: 'VY' },
  xayah:        { name: 'Xayah',        cls: 'marksman', tag: 'XY' },
  zeri:         { name: 'Zeri',         cls: 'marksman', tag: 'ZR' },
  ziggs:        { name: 'Ziggs',        cls: 'mage',     tag: 'ZG' },
  // ── Support
  alistar:      { name: 'Alistar',      cls: 'tank',     tag: 'AL' },
  bard:         { name: 'Bard',         cls: 'support',  tag: 'BD' },
  blitzcrank:   { name: 'Blitzcrank',   cls: 'tank',     tag: 'BC' },
  brand:        { name: 'Brand',        cls: 'mage',     tag: 'BN' },
  braum:        { name: 'Braum',        cls: 'support',  tag: 'BM' },
  heimerdinger: { name: 'Heimerdinger', cls: 'mage',     tag: 'HD' },
  janna:        { name: 'Janna',        cls: 'support',  tag: 'JN' },
  karma:        { name: 'Karma',        cls: 'support',  tag: 'KR' },
  leona:        { name: 'Leona',        cls: 'tank',     tag: 'LE' },
  lulu:         { name: 'Lulu',         cls: 'support',  tag: 'LU' },
  milio:        { name: 'Milio',        cls: 'support',  tag: 'MI' },
  nami:         { name: 'Nami',         cls: 'support',  tag: 'NM' },
  pyke:         { name: 'Pyke',         cls: 'assassin', tag: 'PY' },
  rakan:        { name: 'Rakan',        cls: 'support',  tag: 'RN' },
  renaissata:   { name: 'Renata',       cls: 'support',  tag: 'RT' },
  senna:        { name: 'Senna',        cls: 'support',  tag: 'SN' },
  seraphine:    { name: 'Seraphine',    cls: 'support',  tag: 'SP' },
  sona:         { name: 'Sona',         cls: 'support',  tag: 'SO' },
  soraka:       { name: 'Soraka',       cls: 'support',  tag: 'SR' },
  tahmkench:    { name: 'Tahm Kench',   cls: 'tank',     tag: 'TK' },
  thresh:       { name: 'Thresh',       cls: 'support',  tag: 'TH' },
  vel:          { name: "Vel'Koz",      cls: 'mage',     tag: 'VZ' },
  velkoz:       { name: "Vel'Koz",      cls: 'mage',     tag: 'VZ' },
  xerath2:      { name: 'Xerath',       cls: 'mage',     tag: 'XR' },
  yuumi:        { name: 'Yuumi',        cls: 'support',  tag: 'YM' },
  zilean:       { name: 'Zilean',       cls: 'support',  tag: 'ZL' },
  zoe2:         { name: 'Zoe',          cls: 'mage',     tag: 'ZO' },
  zyra:         { name: 'Zyra',         cls: 'mage',     tag: 'ZY' },
}

export function getChamp(key: string): { name: string; cls: string; tag: string; color: string } {
  const norm = key.toLowerCase().replace(/[^a-z0-9]/g, '').replace(/\s/g, '')
  const data = CHAMPS_RAW[norm] ?? CHAMPS_RAW[key.toLowerCase()] ?? null
  if (data) {
    return { name: data.name, cls: data.cls, tag: data.tag, color: CLASS_COLORS[data.cls] ?? CLASS_COLORS.fighter }
  }
  // Fallback : initiales + couleur déterministe selon le nom
  const tag = key.replace(/[^a-zA-Z]/g, '').slice(0, 2).toUpperCase() || '??'
  const clsList = Object.keys(CLASS_COLORS)
  const cls = clsList[key.charCodeAt(0) % clsList.length]
  return { name: key, cls, tag, color: CLASS_COLORS[cls] }
}
